//-------------------------------------------------------------------------------------------------
// <auto-generated> 
// Marked as auto-generated so StyleCop will ignore BDD style tests
// </auto-generated>
//-------------------------------------------------------------------------------------------------

#pragma warning disable 169
// ReSharper disable InconsistentNaming
// ReSharper disable UnusedMember.Global
// ReSharper disable UnusedMember.Local

namespace RedBadger.Xpf.Specs.Presentation.PointSpecs
{
    using Machine.Specifications;

    [Subject(typeof(Point))]
    public class when_two_points_are_equal
    {
        private static Point point;

        private static bool result;

        private static Point subject;

        private Establish context = () =>
            {
                subject = new Point(10, 20);
                point = new Point(10, 20);
            };

        private Because of = () => result = point == subject;

        private It should_show_them_as_equal = () => result.ShouldBeTrue();
    }

    [Subject(typeof(Point))]
    public class when_two_points_are_not_equal_in_the_x
    {
        private static Point point;

        private static bool result;

        private static Point subject;

        private Establish context = () =>
            {
                subject = new Point(10, 20);
                point = new Point(11, 20);
            };

        private Because of = () => result = point == subject;

        private It should_show_them_as_equal = () => result.ShouldBeFalse();
    }

    [Subject(typeof(Point))]
    public class when_two_points_are_not_equal_in_the_y
    {
        private static Point point;

        private static bool result;

        private static Point subject;

        private Establish context = () =>
            {
                subject = new Point(10, 20);
                point = new Point(10, 21);
            };

        private Because of = () => result = point == subject;

        private It should_show_them_as_equal = () => result.ShouldBeFalse();
    }

    [Subject(typeof(Point))]
    public class when_a_vector_is_added
    {
        private static Point result;

        private static Point subject;

        private Establish context = () => subject = new Point(10, 20);

        private Because of = () => result = subject + new Vector(11, 12);

        private It should_add_the_vector_to_the_point = () => result.ShouldEqual(new Point(21, 32));
    }

    [Subject(typeof(Point))]
    public class when_a_vector_is_subtracted
    {
        private static Point result;

        private static Point subject;

        private Establish context = () => subject = new Point(10, 20);

        private Because of = () => result = subject - new Vector(11, 12);

        private It should_subtract_the_vector_from_the_point = () => result.ShouldEqual(new Point(-1, 8));
    }

    [Subject(typeof(Point))]
    public class when_a_point_is_subtracted
    {
        private static Vector result;

        private static Point subject;

        private Establish context = () => subject = new Point(10, 20);

        private Because of = () => result = subject - new Point(11, 12);

        private It should_subtract_the_vector_from_the_point = () => result.ShouldEqual(new Vector(-1, 8));
    }

    [Subject(typeof(Point))]
    public class when_a_point_is_cast_to_a_Size
    {
        private static Size result;

        private static Point subject;

        private Establish context = () => subject = new Point(10, 20);

        private Because of = () => result = (Size)subject;

        private It should_result_in_an_equivalent_Size = () => result.ShouldEqual(new Size(10, 20));
    }

    [Subject(typeof(Point))]
    public class when_a_point_is_cast_to_a_Vector
    {
        private static Vector result;

        private static Point subject;

        private Establish context = () => subject = new Point(10, 20);

        private Because of = () => result = (Vector)subject;

        private It should_result_in_an_equivalent_Size = () => result.ShouldEqual(new Vector(10, 20));
    }
}