//-------------------------------------------------------------------------------------------------
// <auto-generated> 
// Marked as auto-generated so StyleCop will ignore BDD style tests
// </auto-generated>
//-------------------------------------------------------------------------------------------------

#pragma warning disable 169
// ReSharper disable InconsistentNaming
// ReSharper disable UnusedMember.Global
// ReSharper disable UnusedMember.Local

namespace RedBadger.Xpf.Specs.Controls.GridSpecs.Star
{
    using Machine.Specifications;

    using Moq;

    using RedBadger.Xpf.Controls;

    public abstract class a_Star_Grid_with_two_rows_and_two_columns : a_Grid
    {
        protected static Mock<UIElement> BottomLeftChild;

        protected static Mock<UIElement> BottomRightChild;

        protected static ColumnDefinition ColumnOneDefinition;

        protected static ColumnDefinition ColumnTwoDefinition;

        protected static RowDefinition RowOneDefinition;

        protected static RowDefinition RowTwoDefinition;

        protected static Mock<UIElement> TopLeftChild;

        protected static Mock<UIElement> TopRightChild;

        private Establish context = () =>
            {
                ColumnOneDefinition = new ColumnDefinition();
                Subject.ColumnDefinitions.Add(ColumnOneDefinition);

                ColumnTwoDefinition = new ColumnDefinition();
                Subject.ColumnDefinitions.Add(ColumnTwoDefinition);

                RowOneDefinition = new RowDefinition();
                Subject.RowDefinitions.Add(RowOneDefinition);

                RowTwoDefinition = new RowDefinition();
                Subject.RowDefinitions.Add(RowTwoDefinition);

                TopLeftChild = new Mock<UIElement> { CallBase = true };
                TopLeftChild.Object.Width = 1;
                TopLeftChild.Object.Height = 2;
                TopLeftChild.Object.HorizontalAlignment = HorizontalAlignment.Left;
                TopLeftChild.Object.VerticalAlignment = VerticalAlignment.Top;
                Grid.SetColumn(TopLeftChild.Object, 0);
                Grid.SetRow(TopLeftChild.Object, 0);

                TopRightChild = new Mock<UIElement> { CallBase = true };
                TopRightChild.Object.Width = 3;
                TopRightChild.Object.Height = 4;
                TopRightChild.Object.HorizontalAlignment = HorizontalAlignment.Left;
                TopRightChild.Object.VerticalAlignment = VerticalAlignment.Top;
                Grid.SetColumn(TopRightChild.Object, 1);
                Grid.SetRow(TopRightChild.Object, 0);

                BottomLeftChild = new Mock<UIElement> { CallBase = true };
                BottomLeftChild.Object.Width = 5;
                BottomLeftChild.Object.Height = 6;
                BottomLeftChild.Object.HorizontalAlignment = HorizontalAlignment.Left;
                BottomLeftChild.Object.VerticalAlignment = VerticalAlignment.Top;
                Grid.SetColumn(BottomLeftChild.Object, 0);
                Grid.SetRow(BottomLeftChild.Object, 1);

                BottomRightChild = new Mock<UIElement> { CallBase = true };
                BottomRightChild.Object.Width = 7;
                BottomRightChild.Object.Height = 8;
                BottomRightChild.Object.HorizontalAlignment = HorizontalAlignment.Left;
                BottomRightChild.Object.VerticalAlignment = VerticalAlignment.Top;
                Grid.SetColumn(BottomRightChild.Object, 1);
                Grid.SetRow(BottomRightChild.Object, 1);

                Subject.Children.Add(TopLeftChild.Object);
                Subject.Children.Add(TopRightChild.Object);
                Subject.Children.Add(BottomLeftChild.Object);
                Subject.Children.Add(BottomRightChild.Object);
            };
    }
}