#region License
/* The MIT License
 *
 * Copyright (c) 2011 Red Badger Consulting
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
*/
#endregion

//-------------------------------------------------------------------------------------------------
// <auto-generated> 
// Marked as auto-generated so StyleCop will ignore BDD style tests
// </auto-generated>
//-------------------------------------------------------------------------------------------------

#pragma warning disable 169
// ReSharper disable InconsistentNaming
// ReSharper disable UnusedMember.Global
// ReSharper disable UnusedMember.Local

namespace RedBadger.Xpf.Specs.Controls.GridSpecs.Auto
{
    using Machine.Specifications;

    using RedBadger.Xpf.Controls;

    [Subject(typeof(Grid), "Arrange")]
    public class when_arranging_two_rows_and_two_columns : an_Auto_Grid_with_two_rows_and_two_columns
    {
        private Establish context = () => Subject.Measure(AvailableSize);

        private Because of = () => Subject.Arrange(new Rect(AvailableSize));

        private It should_1_layout_the_top_left_child_correctly =
            () => TopLeftChild.Object.VisualOffset.ShouldEqual(Vector.Zero);

        private It should_2_layout_the_top_right_child_correctly =
            () => TopRightChild.Object.VisualOffset.ShouldEqual(new Vector(50, 0));

        private It should_3_layout_the_bottom_left_child_correctly =
            () => BottomLeftChild.Object.VisualOffset.ShouldEqual(new Vector(0, 80));

        private It should_4_layout_the_bottom_right_child_correctly =
            () => BottomRightChild.Object.VisualOffset.ShouldEqual(new Vector(50, 80));
    }

    [Subject(typeof(Grid), "Arrange")]
    public class when_arranging_two_rows_and_two_columns_with_minimum_values_which_are_greater_than_their_children :
        an_Auto_Grid_with_two_rows_and_two_columns
    {
        private const double MinHeight = 90;

        private const double MinWidth = 80;

        private Establish context = () =>
            {
                ColumnOneDefinition.MinWidth = MinWidth;
                ColumnTwoDefinition.MinWidth = MinWidth;

                RowOneDefinition.MinHeight = MinHeight;
                RowTwoDefinition.MinHeight = MinHeight;

                Subject.Measure(AvailableSize);
            };

        private Because of = () => Subject.Arrange(new Rect(AvailableSize));

        private It should_layout_the_bottom_left_child_correctly =
            () => BottomLeftChild.Object.VisualOffset.ShouldEqual(new Vector(0, MinHeight));

        private It should_layout_the_bottom_right_child_correctly =
            () => BottomRightChild.Object.VisualOffset.ShouldEqual(new Vector(MinWidth, MinHeight));

        private It should_layout_the_top_left_child_correctly =
            () => TopLeftChild.Object.VisualOffset.ShouldEqual(Vector.Zero);

        private It should_layout_the_top_right_child_correctly =
            () => TopRightChild.Object.VisualOffset.ShouldEqual(new Vector(MinWidth, 0));
    }

    [Subject(typeof(Grid), "Arrange")]
    public class when_arranging_two_rows_and_two_columns_with_maximum_values_which_are_less_than_their_children :
        an_Auto_Grid_with_two_rows_and_two_columns
    {
        private const double MaxHeight = 9;

        private const double MaxWidth = 8;

        private Establish context = () =>
            {
                ColumnOneDefinition.MaxWidth = MaxWidth;
                ColumnTwoDefinition.MaxWidth = MaxWidth;

                RowOneDefinition.MaxHeight = MaxHeight;
                RowTwoDefinition.MaxHeight = MaxHeight;

                Subject.Measure(AvailableSize);
            };

        private Because of = () => Subject.Arrange(new Rect(AvailableSize));

        private It should_layout_the_bottom_left_child_correctly =
            () => BottomLeftChild.Object.VisualOffset.ShouldEqual(new Vector(0, MaxHeight));

        private It should_layout_the_bottom_right_child_correctly =
            () => BottomRightChild.Object.VisualOffset.ShouldEqual(new Vector(MaxWidth, MaxHeight));

        private It should_layout_the_top_left_child_correctly =
            () => TopLeftChild.Object.VisualOffset.ShouldEqual(Vector.Zero);

        private It should_layout_the_top_right_child_correctly =
            () => TopRightChild.Object.VisualOffset.ShouldEqual(new Vector(MaxWidth, 0));
    }
}
