//-------------------------------------------------------------------------------------------------
// <auto-generated> 
// Marked as auto-generated so StyleCop will ignore BDD style tests
// </auto-generated>
//-------------------------------------------------------------------------------------------------

#pragma warning disable 169
// ReSharper disable InconsistentNaming
// ReSharper disable UnusedMember.Global
// ReSharper disable UnusedMember.Local

namespace RedBadger.Xpf.Specs.Presentation
{
    using Machine.Specifications;

    using RedBadger.Xpf.Presentation;
    using RedBadger.Xpf.Presentation.Controls;

    [Subject(typeof(DefinitionBase))]
    public class when_a_column_definition_is_initialized
    {
        private const GridUnitType ExpectedGridUnitType = GridUnitType.Pixel;

        private const float ExpectedWidth = 10f;

        private static ColumnDefinition columnDefinition;

        private Because of =
            () =>
            columnDefinition = new ColumnDefinition { Width = new GridLength(ExpectedWidth, ExpectedGridUnitType) };

        private It should_return_column_width_when_user_length_is_requested =
            () => columnDefinition.UserLength.Value.ShouldEqual(ExpectedWidth);

        private It should_return_the_columns_unit_type_when_user_length_is_requested =
            () => columnDefinition.UserLength.GridUnitType.ShouldEqual(ExpectedGridUnitType);
    }

    [Subject(typeof(DefinitionBase))]
    public class when_a_row_definition_is_initialized
    {
        private const GridUnitType ExpectedGridUnitType = GridUnitType.Pixel;

        private const float ExpectedHeight = 10f;

        private static RowDefinition rowDefinition;

        private Because of =
            () => rowDefinition = new RowDefinition { Height = new GridLength(ExpectedHeight, ExpectedGridUnitType) };

        private It should_return_row_height_when_user_length_is_requested =
            () => rowDefinition.UserLength.Value.ShouldEqual(ExpectedHeight);

        private It should_return_the_rows_unit_type_when_user_length_is_requested =
            () => rowDefinition.UserLength.GridUnitType.ShouldEqual(ExpectedGridUnitType);
    }
}