//-------------------------------------------------------------------------------------------------
// <auto-generated> 
// Marked as auto-generated so StyleCop will ignore BDD style tests
// </auto-generated>
//-------------------------------------------------------------------------------------------------

#pragma warning disable 169
// ReSharper disable InconsistentNaming
// ReSharper disable UnusedMember.Global
// ReSharper disable UnusedMember.Local

namespace RedBadger.Xpf.Specs.Presentation.Controls.GridSpecs.Pixel
{
    using System.Windows;

    using Machine.Specifications;

    using RedBadger.Xpf.Presentation.Controls;

    using Vector = RedBadger.Xpf.Presentation.Vector;

    [Subject(typeof(Grid), "Arrange")]
    public class when_arranging_two_rows_and_two_columns_of_type_pixel : a_Grid_with_4_children
    {
        private Establish context = () =>
            {
                Subject.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(5) });
                Subject.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(6) });
                Subject.RowDefinitions.Add(new RowDefinition { Height = new GridLength(7) });
                Subject.RowDefinitions.Add(new RowDefinition { Height = new GridLength(8) });

                Subject.Measure(AvailableSize);
            };

        private Because of = () => Subject.Arrange(new Rect(AvailableSize));

        private It should_layout_the_bottom_left_child_correctly =
            () => BottomLeftChild.Object.VisualOffset.ShouldEqual(new Vector(0, 7));

        private It should_layout_the_bottom_right_child_correctly =
            () => BottomRightChild.Object.VisualOffset.ShouldEqual(new Vector(5, 7));

        private It should_layout_the_top_left_child_correctly =
            () => TopLeftChild.Object.VisualOffset.ShouldEqual(Vector.Zero);

        private It should_layout_the_top_right_child_correctly =
            () => TopRightChild.Object.VisualOffset.ShouldEqual(new Vector(5, 0));
    }
}