//-------------------------------------------------------------------------------------------------
// <auto-generated> 
// Marked as auto-generated so StyleCop will ignore BDD style tests
// </auto-generated>
//-------------------------------------------------------------------------------------------------

#pragma warning disable 169
// ReSharper disable InconsistentNaming
// ReSharper disable UnusedMember.Global
// ReSharper disable UnusedMember.Local

namespace RedBadger.Xpf.Specs.Presentation.Controls.ItemsControlSpecs
{
    using Machine.Specifications;

    using RedBadger.Xpf.Presentation.Controls;

    public abstract class an_ItemsControl
    {
        protected static ItemsControl ItemsControl;

        private Establish context = () => ItemsControl = new ItemsControl();
    }
}