//-------------------------------------------------------------------------------------------------
// <auto-generated> 
// Marked as auto-generated so StyleCop will ignore BDD style tests
// </auto-generated>
//-------------------------------------------------------------------------------------------------

#pragma warning disable 169
// ReSharper disable InconsistentNaming
// ReSharper disable UnusedMember.Global
// ReSharper disable UnusedMember.Local

namespace RedBadger.Xpf.Specs.Presentation.Controls
{
    using Machine.Specifications;

    using Moq;

    using RedBadger.Xpf.Presentation;
    using RedBadger.Xpf.Presentation.Controls;

    using It = Machine.Specifications.It;

    public abstract class a_ContentControl
    {
        protected static ContentControl ContentControl;

        private Establish context = () => ContentControl = new ContentControl();
    }

    [Subject(typeof(ContentControl))]
    public class when_content_is_added : a_ContentControl
    {
        private static Mock<IElement> childContent;

        private Establish context = () =>
            {
                ContentControl.Measure(Size.Empty);
                childContent = new Mock<IElement>();
            };

        private Because of = () => ContentControl.Content = childContent.Object;

        private It should_invalidate_measure = () => ContentControl.IsMeasureValid.ShouldBeFalse();

        private It should_mark_itself_as_the_visual_parent =
            () => childContent.VerifySet(element => element.VisualParent = ContentControl);
    }
}