//-------------------------------------------------------------------------------------------------
// <auto-generated> 
// Marked as auto-generated so StyleCop will ignore BDD style tests
// </auto-generated>
//-------------------------------------------------------------------------------------------------

#pragma warning disable 169
// ReSharper disable InconsistentNaming
// ReSharper disable UnusedMember.Global
// ReSharper disable UnusedMember.Local

namespace RedBadger.Xpf.Specs.Presentation.Controls
{
    using Machine.Specifications;

    using Microsoft.Xna.Framework;

    using Moq;

    using RedBadger.Xpf.Graphics;
    using RedBadger.Xpf.Media;
    using RedBadger.Xpf.Presentation;
    using RedBadger.Xpf.Presentation.Controls;

    using It = Machine.Specifications.It;

    public abstract class a_Panel
    {
        protected static Panel Panel;

        protected static RootElement RootElement;

        protected static Mock<ISpriteBatch> SpriteBatch;

        private Establish context = () =>
            {
                SpriteBatch = new Mock<ISpriteBatch>();
                RootElement = new RootElement(new Rect(new Size(100, 100)));
                Panel = new Panel();
                RootElement.Content = Panel;
            };
    }

    [Subject(typeof(Panel), "Background")]
    public class when_panel_background_is_not_specified : a_Panel
    {
        private Because of = () =>
            {
                RootElement.Update();
                RootElement.Draw(SpriteBatch.Object);
            };

        private It should_default_to_white =
            () =>
            SpriteBatch.Verify(batch => batch.Draw(Moq.It.IsAny<ITexture2D>(), Moq.It.IsAny<Rectangle>(), Color.White));

        private It should_render_the_background_in_the_right_place = () =>
            {
                var area = new Rectangle(
                    (int)Panel.VisualOffset.X, 
                    (int)Panel.VisualOffset.Y, 
                    (int)Panel.ActualWidth, 
                    (int)Panel.ActualHeight);

                SpriteBatch.Verify(
                    batch =>
                    batch.Draw(
                        Moq.It.IsAny<ITexture2D>(), 
                        Moq.It.Is<Rectangle>(rectangle => rectangle.Equals(area)), 
                        Moq.It.IsAny<Color>()));
            };
    }

    [Subject(typeof(Panel), "Background")]
    public class when_panel_background_is_specified : a_Panel
    {
        private static readonly SolidColorBrush expectedBackground = new SolidColorBrush(Color.Blue);

        private Because of = () =>
            {
                Panel.Background = expectedBackground;
                RootElement.Update();
                RootElement.Draw(SpriteBatch.Object);
            };

        private It should_render_the_background_in_the_right_place = () =>
            {
                var area = new Rectangle(
                    (int)Panel.VisualOffset.X, 
                    (int)Panel.VisualOffset.Y, 
                    (int)Panel.ActualWidth, 
                    (int)Panel.ActualHeight);

                SpriteBatch.Verify(
                    batch =>
                    batch.Draw(
                        Moq.It.IsAny<ITexture2D>(), 
                        Moq.It.Is<Rectangle>(rectangle => rectangle.Equals(area)), 
                        Moq.It.IsAny<Color>()));
            };

        private It should_render_with_the_specified_background_color =
            () =>
            SpriteBatch.Verify(
                batch => batch.Draw(Moq.It.IsAny<ITexture2D>(), Moq.It.IsAny<Rectangle>(), expectedBackground.Color));
    }
}