//-------------------------------------------------------------------------------------------------
// <auto-generated> 
// Marked as auto-generated so StyleCop will ignore BDD style tests
// </auto-generated>
//-------------------------------------------------------------------------------------------------

#pragma warning disable 169
// ReSharper disable InconsistentNaming
// ReSharper disable UnusedMember.Global
// ReSharper disable UnusedMember.Local

namespace RedBadger.Xpf.Specs.Presentation.VirtualElementCollectionSpecs
{
    using Machine.Specifications;

    using Moq;

    using RedBadger.Xpf.Presentation;

    using It = Machine.Specifications.It;

    public abstract class a_VirtualElementCollection
    {
        protected static VirtualizingElementCollection Subject;

        private Establish context = () => Subject = new VirtualizingElementCollection();
    }

    [Subject(typeof(VirtualizingElementCollection), "")]
    public class when_virtualizing_an_element : a_VirtualElementCollection
    {
        private Establish context = () => Subject.Add(new Mock<IElement>().Object);

        private Because of = () => Subject.Virtualize(0);

/*
        private It should_virtualize_the_element = () => Subject.IsReal(0).ShouldBeFalse();
*/
    }
}