#region License
/* The MIT License
 *
 * Copyright (c) 2011 Red Badger Consulting
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
*/
#endregion

//-------------------------------------------------------------------------------------------------
// <auto-generated> 
// Marked as auto-generated so StyleCop will ignore BDD style tests
// </auto-generated>
//-------------------------------------------------------------------------------------------------

#pragma warning disable 169
// ReSharper disable InconsistentNaming
// ReSharper disable UnusedMember.Global
// ReSharper disable UnusedMember.Local

namespace RedBadger.Xpf.Specs.ReactivePropertySpecs
{
    using System;

    using Machine.Specifications;

    [Subject(typeof(ReactiveProperty<>), "Default Values")]
    public class when_a_reactive_property_of_reference_type_is_registered_with_no_default
    {
        private static ReactiveProperty<object> SubjectProperty;

        private Because of = () => SubjectProperty = ReactiveProperty<object>.Register("Subject", typeof(object));

        private It should_have_a_default_value_of_null = () => SubjectProperty.DefaultValue.ShouldEqual(null);
    }

    [Subject(typeof(ReactiveProperty<>), "Default Values")]
    public class when_a_reactive_property_of_value_type_is_registered_with_no_default
    {
        private static ReactiveProperty<int> SubjectProperty;

        private Because of = () => SubjectProperty = ReactiveProperty<int>.Register("Subject", typeof(object));

        private It should_have_a_default_value_of_zero = () => SubjectProperty.DefaultValue.ShouldEqual(0);
    }

    [Subject(typeof(ReactiveProperty<>), "Default Values")]
    public class when_a_reactive_property_of_reference_type_is_registered_with_a_default_value
    {
        private const string DefaultValue = "Default Value";

        private static ReactiveProperty<string> SubjectProperty;

        private Because of =
            () => SubjectProperty = ReactiveProperty<string>.Register("Subject", typeof(object), DefaultValue);

        private It should_have_the_registered_default_value =
            () => SubjectProperty.DefaultValue.ShouldEqual(DefaultValue);
    }

    [Subject(typeof(ReactiveProperty<>), "Default Values")]
    public class when_a_reactive_property_of_value_type_is_registered_with_a_default_value
    {
        private static ReactiveProperty<int> SubjectProperty;

        private Because of =
            () => SubjectProperty = ReactiveProperty<int>.Register("Subject", typeof(object), Int32.MaxValue);

        private It should_have_the_registered_default_value =
            () => SubjectProperty.DefaultValue.ShouldEqual(Int32.MaxValue);
    }
}
